### ISSUE TITLE
Install fails using Conda anaconda-nb-extensions channels 

### ISSUE THREAD

**Issue by scollis** [Anaconda-Server/nbpresent#57] opened 2016-02-20 17:21 UTC
OS: OSX
Py2.7

`➜  ~  conda install -c anaconda-nb-extensions nbpresent
Fetching package metadata: ......
Solving package specifications: ................................................
Package plan for installation in environment /Users/scollis/anaconda:

The following NEW packages will be INSTALLED:

    nbpresent: 1.0.0-py27_0

Proceed ([y]/n)? y

Linking packages ...
copying /Users/scollis/anaconda/lib/python2.7/site-packages/nbpresent-1.0.0-py2.7.egg/nbpresent/static/nbpresent -> /Users/scollis/anaconda/share/jupyter/nbextensions/nbpresent
Traceback (most recent call last):
  File "/Users/scollis/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/scollis/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/scollis/anaconda/lib/python2.7/site-packages/nbpresent-1.0.0-py2.7.egg/nbpresent/install.py", line 112, in <module>
    install(**parser.parse_args().__dict__)
  File "/Users/scollis/anaconda/lib/python2.7/site-packages/nbpresent-1.0.0-py2.7.egg/nbpresent/install.py", line 39, in install
    install_nbextension(directory, **kwargs)
  File "/Users/scollis/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 220, in install_nbextension
    _maybe_copy(src, full_dest, verbose)
  File "/Users/scollis/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 53, in _maybe_copy
    shutil.copy2(src, dest)
  File "/Users/scollis/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/scollis/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/scollis/anaconda/lib/python2.7/site-packages/nbpresent-1.0.0-py2.7.egg/nbpresent/static/nbpresent'
Error: Error: post-link failed for: nbpresent-1.0.0-py27_0                                                                                                 |   0%
➜`

Conda env:
`  ~  conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/scollis/anaconda:
#
conda                     3.19.3                   py27_0  `

**Comment by scollis** [comment] 2016-02-20 17:26
Note: works when I use a 3.5 env

**Comment by bollwyvl** [comment] 2016-03-01 14:15
I was never able to reproduce this _particular_ error (though I found lots of conda issues, or rather, issues with how I was using conda!). However, since I did so much work across all the platforms, I'd like to close this one, and re-open with a new issue.

Thanks again @scollis for the report!

**Closed by bollwyvl** 2016-03-01 14:15 UTC
Labels: bug
